version: '2'
services:
  mysqlslave:
    image: mysql:5.7.15
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_ROOT_PASS}
    volumes:
      - ./data/mysql-slave:/var/lib/mysql/
      - ./config/mysql-slave:/etc/mysql/conf.d/
    ports:
      - 3306:3306
