version: '2'
services:
  mysqlmaster:
    image: mysql:5.7.15
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASS}
    volumes:
      - ./data/mysql-master:/var/lib/mysql/
      - ./config/mysql-master:/etc/mysql/conf.d/
    ports:
      - 3306:3306
